// Angular/putrid-grove-angular/src/app/components/items/items.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import Item from 'src/app/models/item';
import { Service } from 'src/app/services/service';
import { ChangeDetectionStrategy, ViewEncapsulation } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import User from 'src/app/models/user';
import ItemRequest from 'src/app/models/itemRequest';
import { Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-items',
  templateUrl: './items.component.html',
  styleUrls: ['./items.component.css'],
})
export class ItemsComponent implements OnInit {
  @ViewChild('closebutton') closebutton: ElementRef<HTMLElement> | undefined;
  public items: Item[] = [];

  constructor(
    public service: Service,
    private fb: FormBuilder,
    private meta: Meta
  ) {
    this.meta.addTag({
      name: 'An overview of all items with their name, descripion, price and owner',
      title: 'Putrid Grove | Items',
    });
  }

  itemForm = this.fb.group({
    name: ['', [Validators.required, Validators.minLength(5)]],
    description: ['', [Validators.required, Validators.minLength(10)]],
    price: [
      '',
      [Validators.required, Validators.pattern('^[0-9]{1,3}([.][0-9]{1,2})?$')],
    ],
    isShared: [false],
  });

  onSubmit(): void {
    this.handleAddItem();
  }

  handleAddItem() {
    this.logValidationErrors();

    if (this.itemForm.valid) {
      const name = !!this.itemForm.value.name ? this.itemForm.value.name! : '';
      const description = !!this.itemForm.value.description
        ? this.itemForm.value.description!
        : '';
      const price = !!this.itemForm.value.price
        ? +this.itemForm.value.price!
        : 0;
      const isShared = !!this.itemForm.value.isShared
        ? this.itemForm.value.isShared!
        : false;
      const isPayedOff = false;
      const iconPath = 'default';
      const payedById = '00000000-0000-0000-0000-000000000001';

      let item = new ItemRequest(
        name,
        description,
        price,
        iconPath,
        isShared,
        isPayedOff,
        payedById
      );

      this.service.addItem(item).subscribe({
        next: () => {
          this.closebutton!.nativeElement.click();
          this.itemForm.reset();
          this.ngOnInit();
        },
      });
    }
  }

  logValidationErrors(group: FormGroup = this.itemForm): void {
    // get all root keys
    Object.keys(group.controls).forEach((key: string) => {
      const abstractControl = group.get(key);

      if (abstractControl instanceof FormGroup) {
        this.logValidationErrors(abstractControl);
      } else {
        // @ts-ignore
        this.formErrors[key] = '';
        if (abstractControl && !abstractControl.valid) {
          // @ts-ignore
          const messages = this.validationMessages[key];

          for (const errorKey in abstractControl.errors) {
            if (errorKey) {
              // @ts-ignore
              this.formErrors[key] += messages[errorKey] + ' ';
            }
          }
        }
      }
    });
  }

  validationMessages = {
    name: {
      required: "Name can't be empty",
      minlength: 'That name is too short',
    },
    description: {
      required: "Description can't be empty",
      minlength: 'The provided description is too short',
    },
    price: {
      required: "Price can't be empty",
      pattern: "That's not a correct price format",
    },
  };
  formErrors = {
    name: '',
    description: '',
    price: '',
  };

  ngOnInit(): void {
    this.items = [];

    this.service.loadItems().subscribe({
      next: (res) => {
        res.forEach((c: any, index: number) => {
          if (index !== 0) {
            this.items.push(c);
          }
        });
      },
    });
  }
}

<div class="w-full h-full flex flex-col items-center">
  <div class="w-full flex flex-col items-center text-gray-700">
    <h1 class="text-5xl uppercase font-semibold mb-2">Items</h1>
  </div>
  <div
    class="w-full h-full mt-10 pb-10 flex justify-center flex-wrap gap-10 overflow-auto"
  >
    <app-item-card *ngFor="let item of items" [item]="item"></app-item-card>
  </div>
</div>
<button
  title="Add item"
  class="fixed z-10 top-20 right-8 uppercase bg-gray-600 rounded-lg py-2 px-5 flex justify-center items-center text-white text-2xl hover:bg-gray-700"
  data-modal-target="default"
  data-modal-toggle="addModal"
  type="button"
>
  Add item
</button>

<!-- Main modal -->
<div
  id="addModal"
  tabindex="-1"
  aria-hidden="true"
  class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full"
>
  <div class="relative w-full h-full max-w-2xl md:h-auto">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow p-6">
      <!-- Modal header -->
      <button
        type="button"
        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 absolute right-2 top-2 inline-flex items-center"
        data-modal-hide="addModal"
        #closebutton
      >
        <svg
          aria-hidden="true"
          class="w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
        <span class="sr-only">Close modal</span>
      </button>
      <div class="uppercase">
        <h1 class="text-2xl mb-3">add item</h1>
      </div>
      <!-- Modal body -->
      <form [formGroup]="itemForm">
        <div class="relative z-0 w-full mb-6 group">
          <input
            type="text"
            name="name"
            id="name"
            formControlName="name"
            class="block py-2.5 px-0 w-full text-sm text-gray-700 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-gray-600 peer"
            placeholder=" "
            [ngClass]="{ 'border-red-500': formErrors.name }"
          />
          <label
            htmlFor="name"
            class="peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-gray-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
            [ngClass]="{ 'text-red-500': formErrors.name }"
          >
            item name
          </label>
          <p *ngIf="formErrors.name" class="mt-2 text-sm text-red-600">
            {{ formErrors.name }}
          </p>
        </div>
        <div class="relative z-0 w-full mb-6 group">
          <textarea
            name="description"
            id="description"
            rows="4"
            formControlName="description"
            class="block py-2.5 px-0 w-full text-sm text-gray-700 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-gray-600 peer"
            [ngClass]="{ 'border-red-500': formErrors.description }"
            placeholder=" "
          ></textarea>
          <label
            htmlFor="description"
            class="peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-gray-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"
            [ngClass]="{ 'text-red-500': formErrors.description }"
          >
            description
          </label>
          <p *ngIf="formErrors.description" class="mt-2 text-sm text-red-600">
            {{ formErrors.description }}
          </p>
        </div>
        <div class="w-full mb-6 flex flex-col justify-center">
          <div class="w-full flex items-center">
            <div class="z-0 mr-6 group">
              <div class="flex">
                <span
                  class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md"
                  [ngClass]="{ 'border-red-500': formErrors.price }"
                >
                  €
                </span>
                <input
                  type="text"
                  id="price"
                  name="price"
                  formControlName="price"
                  class="rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-gray-500 focus:border-gray-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5"
                  [ngClass]="{ 'border-red-500': formErrors.price }"
                  placeholder="price"
                />
              </div>
            </div>
            <div class="z-0 group">
              <label class="relative inline-flex items-center cursor-pointer">
                <input
                  type="checkbox"
                  value=""
                  formControlName="isShared"
                  class="sr-only peer"
                  id="isShared"
                  name="isShared"
                />
                <div
                  class="w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-gray-300 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-gray-600"
                ></div>
                <span class="ml-3 text-sm text-gray-700"
                  >This is a shared item</span
                >
              </label>
            </div>
          </div>
          <p *ngIf="formErrors.price" class="mt-2 text-sm text-red-600">
            {{ formErrors.price }}
          </p>
        </div>
        <button
          type="submit"
          class="text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
          (click)="onSubmit()"
        >
          Add item
        </button>
      </form>
    </div>
  </div>
</div>

// Remix/putrid-grove/app/routes/items.tsx
import { json } from "react-router";
import { db } from "~/utils/db.server";
import { Form, useActionData, useLoaderData, useTransition } from "@remix-run/react";
import { ItemCard } from "~/components/item-card";
import { Modal } from "flowbite-react";
import { useState } from "react";
import { ActionArgs, MetaFunction, redirect } from "@remix-run/node";
import { badRequest } from "~/utils/request.server";

export const meta: MetaFunction = () => ({
  description: "An overview of all items with their name, descripion, price and owner",
  title: "Putrid Grove | Items",
});

export const action = async ({ request }: ActionArgs) => {
  const userId = "00000000-0000-0000-0000-000000000001";

  const form = await request.formData();
  const name = form.get("name");
  const description = form.get("description");
  const priceString = form.get("price");
  const isShared = form.get("isShared") !== null ? true : false;

  if (
    typeof name !== "string" ||
    typeof description !== "string" ||
    typeof priceString !== "string" ||
    typeof isShared !== "boolean"
  ) {
    console.log(name);
    console.log(description);
    console.log(priceString);
    console.log(isShared);

    return badRequest({
      fieldErrors: null,
      fields: null,
      formError: `Form not submitted correctly.`,
    });
  }

  const fieldErrors = {
    name: validateName(name),
    description: validateDescription(description),
    price: validatePrice(priceString),
  };

  const price: number = +priceString;
  const fields = { name, description, price, isShared };

  if (Object.values(fieldErrors).some(Boolean)) {
    return badRequest({
      fieldErrors,
      fields,
      formError: null,
    });
  }

  await db.item.create({
    data: { ...fields, userId: userId, isPayedOff: false, iconPath: "default" },
  });

  return redirect(`/items`);
};

export const loader = async () => {
  const items = await db.item.findMany({
    include: { payedBy: true, itemPayOffs: { include: { user: true } } },
  });

  return json({
    items,
  });
};

function validateName(name: string) {
  if (name.length < 4) {
    return `That name is too short`;
  }
}

function validateDescription(description: string) {
  if (description.length < 20) {
    return `The provided description is too short`;
  }
}

function validatePrice(price: string) {
  if (price.length === 0) {
    return "Price can't be empty";
  }
  if (isNaN(+price)) {
    return `That's not a correct price format`;
  }
}

export default function Items() {
  const data = useLoaderData<typeof loader>();
  const actionData = useActionData<typeof action>();

  const [isShown, setIsShown] = useState(false);

  function onClick() {
    isShown === true ? setIsShown(false) : setIsShown(true);
  }

  function onClose() {
    setIsShown(false);
  }

  return (
    <>
      <div className="w-full h-full flex flex-col items-center">
        <div className="w-full flex flex-col items-center text-gray-700">
          <h1 className="text-5xl uppercase font-semibold mb-2">Items</h1>
        </div>
        <div className="w-full mt-10 pb-10 flex justify-center flex-wrap gap-10">
          {data.items.map((item: any) => (
            <ItemCard item={item} />
          ))}
        </div>
      </div>
      <button
        title="Add item"
        className="fixed z-10 top-20 right-8 uppercase bg-gray-600 rounded-lg py-2 px-5 flex justify-center items-center text-white text-2xl hover:bg-gray-700"
        onClick={onClick}
      >
        Add item
      </button>
      <Modal show={isShown} onClose={onClose}>
        <Modal.Header>
          <div className="uppercase">
            <h1 className="text-2xl">add item</h1>
          </div>
        </Modal.Header>
        <Modal.Body>
          <Form method="post">
            <div className="relative z-0 w-full mb-6 group">
              <input
                type="text"
                name="name"
                id="name"
                className={`block py-2.5 px-0 w-full text-sm text-gray-700 bg-transparent border-0 border-b-2 border-gray-300 appearance-none  focus:outline-none focus:ring-0 focus:border-gray-600 peer ${
                  actionData?.fieldErrors?.name ? "border-red-500" : undefined
                }`}
                placeholder=" "
              />
              <label
                htmlFor="name"
                className={`peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-gray-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6 ${
                  actionData?.fieldErrors?.name ? "text-red-500" : undefined
                }`}
              >
                item name
              </label>
              {actionData?.fieldErrors?.name && (
                <p className="mt-2 text-sm text-red-600">{actionData?.fieldErrors?.name}</p>
              )}
            </div>
            <div className="relative z-0 w-full mb-6 group">
              <textarea
                name="description"
                id="description"
                rows="4"
                className={`block py-2.5 px-0 w-full text-sm text-gray-700 bg-transparent border-0 border-b-2 border-gray-300 appearance-none  focus:outline-none focus:ring-0 focus:border-gray-600 peer ${
                  actionData?.fieldErrors?.description ? "border-red-500" : undefined
                }`}
                placeholder=" "
              />
              <label
                htmlFor="description"
                className={`peer-focus:font-medium absolute text-sm text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-gray-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6 ${
                  actionData?.fieldErrors?.description ? "text-red-500" : undefined
                }`}
              >
                description
              </label>
              {actionData?.fieldErrors?.description && (
                <p className="mt-2 text-sm text-red-600">{actionData?.fieldErrors?.description}</p>
              )}
            </div>
            <div className="w-full mb-6 flex flex-col justify-center">
              <div className="w-full flex items-center">
                <div className={`z-0 mr-6 group`}>
                  <div className="flex">
                    <span
                      className={`inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md ${
                        actionData?.fieldErrors?.price ? "border-red-500" : undefined
                      }`}
                    >
                      €
                    </span>
                    <input
                      type="text"
                      id="price"
                      name="price"
                      className={`rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-gray-500 focus:border-gray-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5 ${
                        actionData?.fieldErrors?.price ? "border-red-50" : undefined
                      }`}
                      placeholder="price"
                    />
                  </div>
                </div>
                <div className="z-0 group">
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input type="checkbox" value="" className="sr-only peer" id="isShared" name="isShared" />
                    <div className="w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-gray-300 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-gray-600"></div>
                    <span className="ml-3 text-sm text-gray-700">This is a shared item</span>
                  </label>
                </div>
              </div>
              {actionData?.fieldErrors?.price && (
                <p className="mt-2 text-sm text-red-600">{actionData?.fieldErrors?.price}</p>
              )}
            </div>
            <button
              type="submit"
              className="text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
            >
              Add item
            </button>
          </Form>
        </Modal.Body>
      </Modal>
    </>
  );
}
