// Angular/putrid-grove-angular/src/app/components/myaccount/myaccount.component.ts
import { Component } from '@angular/core';
import { Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-myaccount',
  templateUrl: './myaccount.component.html',
  styleUrls: ['./myaccount.component.css'],
})
export class MyaccountComponent {
  constructor(private meta: Meta) {
    this.meta.addTag({
      name: "A placeholder for the coming account management system. You'll be able to edit or add information",
      title: 'Putrid Grove | MyAccount',
    });
  }
}

// Remix/putrid-grove/app/routes/myaccount.tsx
import { LinksFunction, MetaFunction } from "@remix-run/node";
import { UnderContruction } from "~/components/under-construction";
import styles from "~/styles/under-construction.css";

export const meta: MetaFunction = () => ({
  description: "A placeholder for the coming account management system. You'll be able to edit or add information",
  title: "Putrid Grove | MyAccount",
});

export const links: LinksFunction = () => {
  return [{ rel: "stylesheet", href: styles }];
};
export default function MyAccount() {
  return <UnderContruction />;
}
