// Remix/putrid-grove/app/routes/users.tsx
import { LinksFunction, MetaFunction } from "@remix-run/node";
import { UnderContruction } from "~/components/under-construction";
import styles from "~/styles/under-construction.css";

export const meta: MetaFunction = () => ({
  description:
    "A placeholder for the coming page to get an overview of all registered users. You'll be able to manage all users.",
  title: "Putrid Grove | User",
});

export const links: LinksFunction = () => {
  return [{ rel: "stylesheet", href: styles }];
};
export default function Users() {
  return <UnderContruction />;
}

// Angular/putrid-grove-angular/src/app/components/users/users.component.ts
import { Component } from '@angular/core';
import { Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.css'],
})
export class UsersComponent {
  constructor(private meta: Meta) {
    this.meta.addTag({
      name: "A placeholder for the coming page to get an overview of all registered users. You'll be able to manage all users.",
      title: 'Putrid Grove | User',
    });
  }
}
