// Remix/putrid-grove/app/routes/payoffs.tsx
import { LinksFunction, MetaFunction } from "@remix-run/node";
import { UnderContruction } from "~/components/under-construction";
import styles from "~/styles/under-construction.css";

export const meta: MetaFunction = () => ({
  description:
    "A placeholder for the coming payoff system where you'll be able to see all your current payoffs and where you will be able to add a payment.",
  title: "Putrid Grove | Payoffs",
});

export const links: LinksFunction = () => {
  return [{ rel: "stylesheet", href: styles }];
};
export default function Payoffs() {
  return <UnderContruction />;
}

// Angular/putrid-grove-angular/src/app/components/payoffs/payoffs.component.ts
import { Component } from '@angular/core';
import { Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-payoffs',
  templateUrl: './payoffs.component.html',
  styleUrls: ['./payoffs.component.css']
})
export class PayoffsComponent {
  constructor(private meta: Meta) {
    this.meta.addTag({
      name: "A placeholder for the coming payoff system where you'll be able to see all your current payoffs and where you will be able to add a payment.",
      title: 'Putrid Grove | Payoffs',
    });
  }
}
