// Remix/putrid-grove/app/components/dashboard/header.tsx
export function Header({ quote }: { quote: string }) {
  return (
    <div className="w-full flex justify-center">
      <div className="header flex flex-col items-center w-max">
        <h1 className="text-5xl font-semibold uppercase text-gray-500">
          Welcome to <span className="ml-4 text-gray-700 font-bold">Putrid Grove</span>
        </h1>
        <div className="w-7/12 text-lg text-gray-700 text-center mt-24">{quote}</div>
      </div>
    </div>
  );
}

// Angular/putrid-grove-angular/src/app/components/dashboard/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  @Input() quote!: string;
}

<div class="w-full break-words flex justify-center">
  <div class="header flex flex-col items-center">
    <h1 class="text-5xl font-semibold uppercase text-gray-500">
      Welcome to
      <span class="ml-4 text-gray-700 font-bold">Putrid Grove</span>
    </h1>
    <div class="w-7/12 text-lg text-gray-700 text-center mt-24">
      {{ quote }}
    </div>
  </div>
</div>
